name: Android build

on:
  workflow_run:
    workflows: [ "common" ]
    types:
      - completed

jobs:

  android_build:
    runs-on: ubuntu-latest
    needs: common

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.13.0
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android apk
        run: flutter build apk --release

      #      - name: Upload code coverage report
      #        uses: codecov/codecov-action@v2
      #        with:
      #          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Android build
          path: build/app/outputs/flutter-apk/app-release.apk