name: Github Action Ci/CD

on:
  push:
    branches:
      - main

jobs:

  common:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.13.0
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: lint
        run: flutter analyze lib

      - name: test with coverage
        run: flutter test --coverage --concurrency=${CPU_COUNT}