name: IOS build

on:
  workflow_run:
    workflows: [ "common" ]
    types:
      - completed

jobs:

  ios-build:
    runs-on: macos-latest
    needs: common

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.13.0
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build ios IPA
        run: flutter build ios --no-codesign

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: IOS build
          path: build/ios/iphoneos/Runner.app